version: "3.9"
services:
  locallife:
    build: 
      context: .
      network: host
    volumes:
      - type: volume
        source: locallifelog
        target: /app/log
        volume:
          nocopy: true
    ports:
      - "8080:8080"
  
volumes:
  locallifelog:
# docker-compose up
